spring.application.name=Hanok Website
spring.profiles.active=dev
spring.jpa.properties.jakarta.persistence.validation.mode=callback

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:hanok
spring.datasource.username=hanok
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
#logging.file.path=./logs
#logging.file.name=my-app.log
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
app.order.pickup.cutoff.hour=14
app.order.pickup.cutoff.minute=00
app.order.pickup.timezone=Europe/London
app.order.pickup.min-lead-days=3
app.order.pickup.max-months=3
store.opening-hours.MONDAY=9-19
store.opening-hours.TUESDAY=9-19
store.opening-hours.WEDNESDAY=9-19
store.opening-hours.THURSDAY=9-19
store.opening-hours.FRIDAY=9-19
store.opening-hours.SATURDAY=10-19
store.opening-hours.SUNDAY=10-18